sudo: required
language: node_js
node_js:
- '4.2.2'
before_install:
- gem install sass
- source ~/.rvm/scripts/rvm && rvm use 2.0.0
- gem install scss_lint
- npm install -g npm
- npm install promise
before_script:
- npm install -g gulp
script:
- gulp deploy
- npm test
- gulp coveralls
